@url = "http://localhost:3000/"

GET http://localhost:3000/flight HTTP/1.1;
######################################
GET http://localhost:3000/flight/flight to Canada
#####################################
POST http://localhost:3000/flight HTTP/1.1
Content-Type: application/json

{
      "title": "flight to Canada",
      "time": "2pm",
      "price": 36000,
      "date": "26-06-2022"
}
######
PUT http://localhost:3000/flight/flight to Canada
Content-Type: application/json

{      
      "time": "5pm",
      "price": 16000,
      "date": "26-06-2022"
}
#####
DELETE http://localhost:3000/flight/flight to canada
